
NURSE_SPEED_MPS = 1

# visualisation
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

MAP_SURF_WIDTH = 650
MAP_SURF_HEIGHT = 500

TEXT_SURF_WIDTH = 100
TEXT_SURF_HEIGHT = 200

TEXT_SURF_OFFSET = 20

ROOM_SIDE_METERS = 4

NURSE_RADIUS_METERS = ROOM_SIDE_METERS / 14